### ISSUE TITLE
Multiple language select on awesome selfhosted form

### ISSUE THREAD

**Issue by joubertredrat** [joubertredrat/redrat.com.br#2]
Hi,

Have a lot of selfhosted soluctions that use more than one language, then is necessary to configure multiselect on form.

@nodiscc @Kickball

**Comment by Kickball** [comment]
Sounds good, will this be possible?

**Comment by joubertredrat** [comment]
Hi guys,

@Kickball yes, is possible

**Comment by joubertredrat** [comment]
I'm looking here, have applications that have more than 1 license too?

**Comment by nodiscc** [comment]
Yes. Applications can have multiple licenses (I see GPLv3/Other, WTFPL/Other, there's an Apache 2.0/Other wpplication in a pending PR...)

**Comment by joubertredrat** [comment]
Okay, I will provide muilti selection to licenses too

**Comment by joubertredrat** [comment]
Fixed on commit 9516b9b
