### ISSUE TITLE
mine version of awesome sysadmin or another name

### ISSUE THREAD

**Issue by joubertredrat** [joubertredrat/redrat.com.br#3]
@nodiscc @Kickball

If awesome-sysadmin continues as idle or abandoned I will continue on my fork or create repo with another name.

I was a collaborator at that repository, but I left because I disagree with some of the rules from n1trux. In my point of view, the list need to be impartial and not display what I consider awesome.

As example, he wanted to remove Zimbra from list only because find it hard to install, but isn't, is easy to install.

Then, if I start this, you help me to display repository to world?

**Comment by nodiscc** [comment]
Hello, I think duplicating efforts is not the way to go. @n1trux's fork has active contributors and can be considered a well maintained fork. Zimbra has not been removed afaik. Personnally I wouldn't add yet another fork of awesome-sysadmin to awesome-selfhosted links, except if it brings _significant_ value (read _many useful changes_).

> the list need to be impartial and not display what I consider awesome

n1trux seems to do a good job at ensuring submitted software is high quality. I think you should make your case on his issue tracker if you really need something changed there. Forking should be a last resort.

**Comment by n1trux** [comment]
I didn't remove Zimbra, I only asked if it's really awesome. I had a lot of issues with it a few years ago, if the installation process is now better, it can certainly stay. If you feel that my treatment of contributors is unfair, I'm very sorry.

The "rules" (guidelines, rather) I imposed on the list are to ensure quality of the submitted applications. I don't have a problem with anyone objecting these guidelines, especially if the supporters of changing direction outnumber me or have compelling arguments. If you have an issue with the submission guidelines, feel free to create an Issue on my awesome-sysadmin repo.

[to be continued]

**Comment by joubertredrat** [comment]
@nodiscc Okay, if you consider sysadmin as active, I will not speak any more.

anyway, I will start my repository in https://github.com/joubertredrat/awesome-devops 
If you ever considered a good repository, you're welcome.

@n1trux you saw on Gitter that would remove Zimbra because you consider hard to install and not amazing .... Zimbra is the largest open source project about collaborative server with e-mail, calendar, messaging and other.

I do not know why you have not removed, I do not agree with this rules, the rules of selfhosted repo are more flexible, but we live in an open source world, just create my repository.

Then, problem solved

**Comment by n1trux** [comment]
> I do not know why you have not removed

Because you objected to it.

> I do not agree with this rules

Again, these are guidelines. With what exactly do you disagree?

> the rules of selfhosted repo are more flexible

Yes, because they don't need to be more restrictive, since the scope of the project isn't as broad and there aren't as many projects approved. That may or may not change in the future.

> we live in an open source world, just create my repository.

Okay, of course you have any right to do that. I don't understand why you want to duplicate efforts, though.
